### PR TITLE
feat: add chart for captain-hook as a webhook relay for infra

### PR DESCRIPTION
**Pull request by garethjevans**

### CODE REVIEW

**Review by timja — APPROVED** [review]
this should probably live in jenkinsci and have it's helm chart in https://github.com/jenkinsci/helm-charts but good for now I guess

**Review by oleg-nenashev — COMMENTED** [review]
Have you considered using https://github.com/stakater/GitWebhookProxy ? Not against using a new implementation, but there might be some maintenance overhead

**Comment by timja** [comment]
> Have you considered using [stakater/GitWebhookProxy](https://github.com/stakater/GitWebhookProxy) ? Not against using a new implementation, but there might be some maintenance overhead

I guess the question is does what does that proxy do if jenkins is down? part of captain-hook is storing them and only forwarding them if Jenkins is up

**Comment by garethjevans** [comment]
@oleg-nenashev I wasn't aware of that project.  But from a brief look it does appear to be slightly different.  It doesn't make any attempt to redeliver the hook if jenkins is unavailable for a period of time

I've also added a CRD to aid debuging e.g.

```console
kubectl get hooks
```

will display the webhook events its currently processing.

**Comment by olblak** [comment]
> this should probably live in jenkinsci and have it's helm chart in https://github.com/jenkinsci/helm-charts but good for now I guess

I would definitely see it under the jenkinsci organisation, it will bring visibility on this tool and maybe attract contributors and why not also integrate it in the jenkinsci helm chart once stable enough

**Comment by garethjevans** [comment]
@timja totally agree with the location of the chart etc, just want to do a little more testing against some real repos to see how it handles the restarts.

Need to speak to @olblak about using a different TLS host and firewall rules to allow requests in.

**Review by olblak — APPROVED** [review]

**Review by markyjackson-taulia — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]

**Pull request merged**
