### PR TITLE
chore: list all releases by clusters and get rid of the helmfile.d folder

### PR DESCRIPTION
**Pull request by lemeurherve**
Ref: https://github.com/jenkins-infra/charts/issues/1675

### CODE REVIEW

**Comment by lemeurherve** [comment]
WIP: kinda blocked by updatecli as I don't see how I can update one of the releases in the same helmfile, and without keeping an index of the charts order :'(

For example, [here](https://github.com/jenkins-infra/charts/blob/main/updatecli/updatecli.d/charts/accountapp.yaml#L15) instead of
```
targets:
  updateChartVersion:
    name: "Update the chart version for accountapp"
    kind: yaml
    spec:
      file: helmfile.d/accountapp.yaml
      key: releases[0].version
```
I would need to be abble to specify something like that:
```
targets:
  updateChartVersion:
    name: "Update the chart version for accountapp"
    kind: yaml
    spec:
      file: clusters/publick8s.yaml
      key: releases[].version
      where:
		field: release.name
		eq: accountapp
```

**Comment by lemeurherve** [comment]
FTR:
image

Will need to use official jenkins chart instead of [the custom one](https://github.com/jenkins-infra/public-charts/blob/main/charts/jenkins/requirements.yaml#L5-L17).

**Comment by halkeye** [comment]
Isn't the "custom one" just the official chart, pinned to a specific version, and extra stuff added to it? Its like a sub class.

**Comment by dduportal** [comment]
> Isn't the "custom one" just the official chart, pinned to a specific version, and extra stuff added to it? Its like a sub class.

Correct. Herve and I are considering decoupling and calling directly the official jenkins helm chart. That would mean 2 releases for infra.ci for instance: one applying the jenkins helm chart + one to apply the "custom resources". You can look at the cert-manager + acme releases in the cert-manager.yaml manifest: it's the same and it's way simpler to express and control.

**Comment by lemeurherve** [comment]
Corresponding (wip) PR: https://github.com/jenkins-infra/charts/pull/1685

**Comment by lemeurherve** [comment]
I don't understand the errors I've got in [the last diff](https://infra.ci.jenkins.io/blue/organizations/jenkins/charts/detail/PR-1683/10/pipeline):
```
in clusters/publick8s.yaml: 9 errors:
err 0: command "/usr/local/bin/helm" exited with non-zero status:

PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: diff (4 bytes)
  2: upgrade (7 bytes)
  3: --reset-values (14 bytes)
  4: --allow-unreleased (18 bytes)
  5: prometheus (10 bytes)
  6: prometheus-community/prometheus (31 bytes)
  7: --version (9 bytes)
  8: 14.11.1 (7 bytes)
  9: --namespace (11 bytes)
  10: prometheus (10 bytes)
  11: --values (8 bytes)
  12: /tmp/helmfile297636863/prometheus-prometheus-values-5b9f496695 (62 bytes)
  13: --suppress-secrets (18 bytes)
  14: --no-color (10 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: Failed to render chart: signal: killed: 
  Error: plugin "diff" exited with error

COMBINED OUTPUT:
  Error: Failed to render chart: signal: killed: 
  Error: plugin "diff" exited with error
err 1: command "/usr/local/bin/helm" exited with non-zero status:

```

Locally I've got another type of error:
```
ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: Failed to get release cert-manager in namespace cert-manager: exit status 1: Error: query: failed to query with labels: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 3; INTERNAL_ERROR
  Error: plugin "diff" exited with error

COMBINED OUTPUT:
  Error: Failed to get release cert-manager in namespace cert-manager: exit status 1: Error: query: failed to query with labels: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 3; INTERNAL_ERROR
  Error: plugin "diff" exited with error
```

**Review by dduportal — APPROVED** [review]
Great work 🚀

**Pull request merged**
