### PR TITLE
Switch to latest plugin-site-api that reads plugin docs from wiki export

### PR DESCRIPTION
**Pull request by halkeye**

### CODE REVIEW

**Comment by zbynek** [comment]
Hm, the wiki content doesn't look right here:
https://plugins.jenkins.io/api/plugin/deploy/ and it's using the new repository already.

**Comment by halkeye** [comment]
Yea generate data gets run all the time after its merged. the code that reads from anything other than jenkinsci repo isn't live yet. Waiting for approval to deploy to k8s

**Comment by halkeye** [comment]
Once this is live, or I spin up a local container I'll submit my pr for plugin site and things should work again

**Review by zbynek — APPROVED** [review]

**Comment by halkeye** [comment]
sweet, with https://github.com/jenkins-infra/plugin-site-api/commit/c84f6549eb53a8e87b4126ce1f54d80399429626 we should see content on api 🤞

**Pull request merged**
