### PR TITLE
Add confluence credentials

### PR DESCRIPTION
**Pull request by halkeye**
Didn't actually test on my cluster, but looks good to eyeball

$ helm upgrade -i jenkins-wiki-exporter . --dry-run --debug --set=ingress.enabled=false --set=confluence.username=fakeuser --set=confluence.password=fakepass

```

[debug] Created tunnel using local port: '32923'

[debug] SERVER: "127.0.0.1:32923"

Release "jenkins-wiki-exporter" does not exist. Installing it now.
[debug] CHART PATH: /home/halkeye/git/jenkins-infra/charts/charts/jenkins-wiki-exporter

NAME:   jenkins-wiki-exporter
REVISION: 1
RELEASED: Tue Oct 22 22:46:50 2019
CHART: jenkins-wiki-exporter-0.1.0
USER-SUPPLIED VALUES:
confluence:
  password: fakepass
  username: fakeuser
ingress:
  enabled: false

COMPUTED VALUES:
affinity: {}
confluence:
  password: fakepass
  username: fakeuser
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: halkeye/jenkins-wiki-exporter
  tag: f2634e1f1b790cbeffce7ca56d0fdf8ca1e8010a
imagePullSecrets: []
ingress:
  enabled: false
nameOverride: ""
nodeSelector: {}
replicaCount: 2
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
service:
  port: 80
  type: ClusterIP
tolerations: []

HOOKS:
---
apiVersion: v1
kind: Pod
metadata:
  name: "jenkins-wiki-exporter-test-connection"
  labels:
    app.kubernetes.io/name: jenkins-wiki-exporter
    helm.sh/chart: jenkins-wiki-exporter-0.1.0
    app.kubernetes.io/instance: jenkins-wiki-exporter
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['jenkins-wiki-exporter:80']
  restartPolicy: Never
MANIFEST:

---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-wiki-exporter
  labels:
    app.kubernetes.io/name: jenkins-wiki-exporter
    helm.sh/chart: jenkins-wiki-exporter-0.1.0
    app.kubernetes.io/instance: jenkins-wiki-exporter
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
type: Opaque
data:
  confluence_username: ZmFrZXVzZXI=
  confluence_password: ZmFrZXBhc3M=
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-wiki-exporter
  labels:
    app.kubernetes.io/name: jenkins-wiki-exporter
    helm.sh/chart: jenkins-wiki-exporter-0.1.0
    app.kubernetes.io/instance: jenkins-wiki-exporter
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: jenkins-wiki-exporter
    app.kubernetes.io/instance: jenkins-wiki-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-wiki-exporter
  labels:
    app.kubernetes.io/name: jenkins-wiki-exporter
    helm.sh/chart: jenkins-wiki-exporter-0.1.0
    app.kubernetes.io/instance: jenkins-wiki-exporter
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: jenkins-wiki-exporter
      app.kubernetes.io/instance: jenkins-wiki-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jenkins-wiki-exporter
        app.kubernetes.io/instance: jenkins-wiki-exporter
    spec:
      containers:
        - name: jenkins-wiki-exporter
          image: "halkeye/jenkins-wiki-exporter:f2634e1f1b790cbeffce7ca56d0fdf8ca1e8010a"
          imagePullPolicy: IfNotPresent
          env:
            - name: CONFLUENCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: jenkins-wiki-exporter
                  key: confluence_username
            - name: CONFLUENCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jenkins-wiki-exporter
                  key: confluence_password
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
```

### CODE REVIEW

**Comment by halkeye** [comment]
```
 (ssh) odin   wiki-exporter-confluence  …/charts/charts/jenkins-wiki-exporter  helm upgrade -i jenkins-wiki-exporter . --set=confluence.username=fakeuser --set=confluence.password=fakepass  --set=ingress.enabled=false --namespace=chartdev
Release "jenkins-wiki-exporter" does not exist. Installing it now.
NAME:   jenkins-wiki-exporter
LAST DEPLOYED: Tue Oct 22 22:47:55 2019
NAMESPACE: chartdev
STATUS: DEPLOYED

RESOURCES:
==> v1/Deployment
NAME                   READY  UP-TO-DATE  AVAILABLE  AGE
jenkins-wiki-exporter  0/2    2           0          0s

==> v1/Pod(related)
NAME                                    READY  STATUS             RESTARTS  AGE
jenkins-wiki-exporter-76b76d7c79-l94w2  0/1    ContainerCreating  0         0s
jenkins-wiki-exporter-76b76d7c79-z562l  0/1    ContainerCreating  0         0s

==> v1/Secret
NAME                   TYPE    DATA  AGE
jenkins-wiki-exporter  Opaque  2     0s

==> v1/Service
NAME                   TYPE       CLUSTER-IP    EXTERNAL-IP  PORT(S)  AGE
jenkins-wiki-exporter  ClusterIP  10.102.201.9  <none>       80/TCP   0s


NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace chartdev -l "app.kubernetes.io/name=jenkins-wiki-exporter,app.kubernetes.io/instance=jenkins-wiki-exporter" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80

(ssh) odin   wiki-exporter-confluence  …/charts/charts/jenkins-wiki-exporter  kail -n chartdev
chartdev/jenkins-wiki-exporter-76b76d7c79-l94w2[jenkins-wiki-exporter]:
chartdev/jenkins-wiki-exporter-76b76d7c79-l94w2[jenkins-wiki-exporter]: > confluence-to-md-web@1.0.0 start /home/node
chartdev/jenkins-wiki-exporter-76b76d7c79-l94w2[jenkins-wiki-exporter]: > node index.js
chartdev/jenkins-wiki-exporter-76b76d7c79-l94w2[jenkins-wiki-exporter]:
chartdev/jenkins-wiki-exporter-76b76d7c79-l94w2[jenkins-wiki-exporter]: {"name":"node:utils","hostname":"jenkins-wiki-exporter-76b76d7c79-l94w2","pid":25,"level":30,"msg":"pandoc 2.7.3\nCompiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1\nDefault user data directory: /home/node/.local/share/pandoc or /home/node/.pandoc\nCopyright (C) 2006-2019 John MacFarlane\nWeb:  http://pandoc.org\nThis is free software; see the source for copying conditions.\nThere is no warranty, not even for merchantability or fitness\nfor a particular purpose.\n","time":"2019-10-23T05:48:19.631Z","v":0}
chartdev/jenkins-wiki-exporter-76b76d7c79-l94w2[jenkins-wiki-exporter]: 3000 is the magic port
chartdev/jenkins-wiki-exporter-76b76d7c79-z562l[jenkins-wiki-exporter]:
chartdev/jenkins-wiki-exporter-76b76d7c79-z562l[jenkins-wiki-exporter]: > confluence-to-md-web@1.0.0 start /home/node
chartdev/jenkins-wiki-exporter-76b76d7c79-z562l[jenkins-wiki-exporter]: > node index.js
chartdev/jenkins-wiki-exporter-76b76d7c79-z562l[jenkins-wiki-exporter]:

```

**Comment by olblak** [comment]
Does your confluence user need anything else that read permission?

**Comment by halkeye** [comment]
Nope

**Comment by olblak** [comment]
Are you behind the jenkins account 'jenkins-wiki-exporter-bot'?
If you share with me your public gpg key, I can create the secrets.yaml and then you'll be able to edit that file yourself

**Comment by halkeye** [comment]
> Are you behind the jenkins account 'jenkins-wiki-exporter-bot'?

no, no idea what that is

> If you share with me your public gpg key, I can create the secrets.yaml and then you'll be able to edit that file yourself

I think i exported it right
```
gpg --armor --export github@gavinmogan.com
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2.0.22 (GNU/Linux)

mQINBFxWFLQBEAC60JhvNIzOPwC4MCrEh8CVQjS7r3/BtfPHacam0SWMsgA/snNo
L6oN3qE2T/U2pzjofZLgwZvkuhV8IQpehm4yF5SgVFcpfNEdEoVWZNPi4c88AhWW
oHSkgqJyAyRSialD2IHaf47dhJTKoosFDqZm9WudTW/tG31xtnEEnwPqeplNLwIK
Ci7ixz0a4Odde8nEDPO/i4fG31F67xuzVjiSdX1gtEG8RgDLUCg0rN1rmfy/S+lg
V6UzfXqd/8TmchwbHir4YJPrWPb5INW2Bxzkbb2JSEMzzysJC3L4fPR4Eql+gv1N
+NCtT0JRp4y1QkC341PLNijTGJpdr4tRc0+9F7WqsNIFKE9GvHbW8xEk0HeHZMP5
frBIVzJlWcS1B0EiIPbqm/j+cX4iM5vKQALpe1w+O7OuVTp4bBFcwjG43Loae6PO
1dibcMegdpYjxB5CX1tHUhCMjbhRrQJUdOekyJh8IXK6iymeqtqy02jMu6Md/JRF
EzX1CdWy8JW+lk0n9dzuJBDqqxSakNYEflZ5vMAn3iRRTr3Ig1fQ7E3LEVIh1F16
Mc5j1NSTosrs2bew42K1yTWbh01cYh2xvrqCeaW7VbYSuHtkjHQU91p2sjcCDtv9
9cMHXrZroqDV/PijKIRRvZ5ywna2bS2QR4Ankf2XHiwesa5mt6LoIJFBywARAQAB
tCJHYXZpbiBNb2dhbiA8Z2F2aW5AZ2F2aW5tb2dhbi5jb20+iQI4BBMBCAAsBQJc
VhS0CRCiZvLT+dYMRQIbAwUJHhM4AAIZAQQLBwkDBRUICgIDBBYAAQIAAI7CD/9g
hdTQsAEPMnFKjHYe3EplceY0CieJkoW0E44eFexwYyCCaQzrYGJ0px1b/NqnzznO
ea0zw2aXTiBSOw9P4oAmglVtbKPx+/b9udBqLDQuK8Xzoc15Mhd3it0KirLy5ui3
ZsWwbvDm+VisNsVSrPJ9QzZ9UZ+Jc58I1HWm1mh+QVqeNgBhr9jmhFmmwE3vE8aD
WJovtDW5vjHk/t1iIiQZhng2x3yuggxx1IPBYk2CLlWJUjwxbBblnWfJ5bSYJOEg
lcPiuux8oVr6KsaSHxFfXnxr2bWkCwOAKbJc1cDOfsu2jHLF2U7we+akrrNXGOrR
b4cZBsPOZJtc1MDFr4VdZfM66NR8nRDT61QN0XRM8bEh2M9BPM3xeeBOQ0HL1S9I
49rWcqFtKI7jS5APHVWqXgN7BC1xbss+B7NyiopnLbULO4PZeETrvFl62wlwtOqn
sx3AB+K/vFmxgclC/grvJ2g6F4DHirIAXpfxKnm7bsgw+R3LU53FPF4lp4z8zrzr
FRGvW8WOhyvV2LnDLJf2TNIM3uWxbehIOuTYn5nIt9DJlmRxXRLp88w+79oO3Vm2
ERCclDelKjcyDJ9mnjU1WZArs/xg+LqZRGnXNCgwRqRMxV0Hk5+dkavhF3rtwFAd
ppZMFAMz0d+jAETk9CrxcNeUjwp6Fkluh3YeuiCLPLQjR2F2aW4gTW9nYW4gPGdp
dGh1YkBnYXZpbm1vZ2FuLmNvbT6JAjUEEwEIACkFAlxWFLQJEKJm8tP51gxFAhsD
BQkeEzgABAsHCQMFFQgKAgMEFgABAgAA4i0P/jFdpXt5YXrmTRdNiWihxRoGjA6I
dpu4A0c2Ua1zguxrpNpiQuNhrWeMxmn5KRYkwADRBJINeJ2SVI9UYVuJAr0XF+E5
aBeQqXL5/PyEa9PR19A563FrbkIM0pXAFON+9EsH7SfRbFSU5NRH+buzuuMHJ06t
PoLRzrHI/dwIhQjjgCkGzQS/P2NayU5apIY4t8tWPR/JnSKcC0cHgSQrwzDTrC69
/qypnl9ZpqZ6gp3BvCnXDZKF5JAC6Kr/OuuaHHeybTkFmejH9YzBCJVddXGY2Jih
84YHLrOSTBdwPx2dNcR4GWsUeqZeIDVfz7kEGFm43FhpxNdrlas9cKgkdJ8rw5Gx
q+AU2Yw8kySsmfAkaBeI/w9lGW1wOYuzynWB+AYOA26DECcWrPGRSDdQ6gPHLRU4
QfQwfl1WCvmqpRTN+y8cecoMTnZfONffOHUVTY9ISZsdHlbDAwBCmaHiEzGAszvL
MDuM4b3hc2Y5FbYt6jHivIhZewp9SAgLdanl9V2uYH68Mjj/KY4jPBkZvMhwMmFk
yJcKDrLp+62Cq8mXoTy52EYKp6gPge9I3zzUNYNMYB7T7Shmrb7Gwa0b3+YlENE8
0u7eH2IXjowltQiwC/Gnzzq7fONJaNnRqSq8LabTFJ7Q8CfPhN8GH2I9LlLMB2Pm
/4uXW+ILw1JmKcgftCBHYXZpbiBNb2dhbiA8Z2l0QGdhdmlubW9nYW4uY29tPokC
NQQTAQgAKQUCXFYUtAkQomby0/nWDEUCGwMFCR4TOAAECwcJAwUVCAoCAwQWAAEC
AAAZYA/+Ky+llEXtTR1xfFeESXwoZuJc41qlH71GmZug7gjzebC83duAGa5/FO4B
ghYhFnawiIHSlyhEnE81/gxA9jVFRKEZMY/RbU2/PW8xzwqhe8QCE7fCKOQSGwbE
M2Gb+/dAwfVERBnqCo6gYytnpw2OpXSKQWW6TgHkksL6mL9OHQv10NiRWQcy4pFo
u5AkoJAUaZNg4sMDPHleg0vMJOO3dpkCvKu9UBo9Rcgfs2AjJ3cTqfK201qyE5aG
VEp9ILaTuEspPeZXEaF/eN3LznAQyJIyl/jBiEFi1M8O2dP2f9+69fiCDj60ISEl
HfzptuAGixPJMgh6ejtsLMb2/SHJ1vR4IdR2/ZJzT7D5PhodOQK/vx8x/54lkwkd
zvw6OePzNXcv545YtAbMfYD1V4aMYIPrZ9tT1n2cbs3P1oORR1RQlFp7u14Eru+c
7CBfiy2H3/9d+aqFLzAumROI8oFLsrn/EFw7utoN7wd55tMis0IcJIh9M3TMyZ1v
lL0nrMyuWUyxjwWYB4cX2f2heShUpBtpgVk7Sog0oIlsZY3iQTwlmjeW0jSQ1nz5
BO8u5hxSJ52C59MVfqup6+kX/YeZ3g6HeCoODaNSXO6mWxBXZ/gKFJp9zTubdi8A
gMlk/k72k+Q+c+xZSCvSST5zOsruoqLM9K5Kt6uCAdPreVAYZq+5Ag0EXFYUtAEQ
ALpd018LLxK4YoAvHbHFs/z1/bvRPzy9p9LJkDSIfzDBnde82AMwLJpLnKfqSXya
OU1LUY5K0ywUycTloDUdiGMJVhEELcuiO+OYebEICdVBcZ1lM9NS6bmISxGpmoXh
EqgVyomC3bDFfuk3I1/L4Xsp3Ke4ZnOBaq7aYss0DCIPXTkI0hOhArdj3T0AwR84
eNBtNcwWqGVZPRw/oT9gji2wJTUdiVA4fOaK0FPDaOcJp2l2uvgvcZqfrCk+b86h
kSP1jpbkiEck6Rf4gznoJ1n4CfGxHSkXkb8D2uoWWKIYOLlLEw3uzZjOwfY1NbOQ
POoniQKUjHV/a1ECb3y6eMxX9Z9GWaqadhOJtrldDbFcFBSXiDm3X9x4yPOLP9Jt
xmOrK7Lyq0sYUqdtiFQfi5tUqecd9sVuFsInyyNQlCw6w32X2ZYeJA95Qz/37xue
SZXmODuxlIxlcaysQMBWNa0t1ul7mVUeT98na7MnhN2buLWlB9spd4AnOIh+QE4+
OIqokIQLtnIwpui2nZrDgZ9V8geES+bbADpIygYnYmbwcANrY+YHop5ngfKCYz/V
8G4GuJ5nKaHXt3L4dSefQC+FWGPEBDA8clLJ/7RpY/gVqE92vF3MkBcINUERj9eE
NYFqJRmDkg7ke59yPcSXkZ4lByzsu1lw/AKzthWzGXE3ABEBAAGJAjUEGAEIACkF
AlxWFLQJEKJm8tP51gxFAhsMBQkeEzgABAsHCQMFFQgKAgMEFgABAgAAB1sQALFS
Q2fp8F8GONuRkpsRaVECIPSDMBH7O7ssv5qqgf2vMed1KRJcNSuhycc/Abz32CXN
NkVQyFxOAH1WZcEtY4X66MvivsPo+lyBvwjOByBU/x/Xox3ML5+med21Aj6T6uuI
C7cvulYiyehDNxmF3IV06R+JBTWXqVWOtQRk93nU4HyQ1nI/0EvYwD5UJ9kBKeLh
DvsJDW87/PNnpUvN1PkwrI3coH1mwOa5d10aApIWxY2W3P31NZtciOki4TpMmrrf
K8gvlRsE2vjSv7Mf1QRkQ7HePtuK286YDYyc+ta+usTpk/Hq5kuimmfKK+h+/9Ms
oAgXiuD+Ttqof/AI68KQpECzxGfTQQNFYpUQud/RLc4n1qEnRb+ls+3Js0gf00Ip
VqscQy2DOxnI6Fvk05iIUv8yuK3qXXk+gNVN6/HoRI0Ej3iHhaQoIZpf/Ue2C33C
pvjv1zhC4Tkn9f18mlj2Ect+SaxX2fSEpgtE0zqDCZdaZur2s+BF8QQS4gkv0cl9
TZFMfbMvHZWplLQS20nM4rzFnClg27NUIjTEnpSsm+YA/OHJliWB8l9UZz/E6Vjb
QYWvyzdZdh1G4pOklW7VeI2Kp8427gu5ewvG+uwiE0zadG4wzmCYzqbuVRcKXjYt
/uGp4TPJtULqMsRrWiAiSteOfqPZss73qQ9s0cwx
=GWl0
-----END PGP PUBLIC KEY BLOCK-----
```

**Pull request merged**
