### PR TITLE
[INFRA-2891] Add the new cik8s cluster

### PR DESCRIPTION
**Pull request by dduportal**
This PR introduces the following changes:

- Add the new cluster `cik8s`, stored in EKS (infra defined in https://github.com/jenkins-infra/aws) under the charts system. Authentication is managed through 2 new secrets credentials:
  - A`kubeconfig` file with an empty context for the current AKS cluster (`publick8s` because it uses the internal API + serviceAccountToken mounted in the pipeline pods), and a context for EKS cluster - https://github.com/jenkins-infra/charts/pull/978
  - An AWS IAM user named `eks_charter`, with admin access to the EKS cluster, but no IAM role associated - https://github.com/jenkins-infra/charts/pull/979
- Switch the pipeline's diff feedback from PR comments to GitHub checks, to avoid alert fatigue. It also provides the "latest" vision.

A bit of cleanup has been done: the `clusters/trustedk8s.yml` had been removed since it was an experiment.

### CODE REVIEW

**Review by markyjackson-taulia — APPROVED** [review]

**Comment by timja** [comment]
ah thanks, no more comment spam ❤️

**Comment by dduportal** [comment]
> ah thanks, no more comment spam ❤️
@timja Credits due to @jglick and is eagle eyes for this change ;)

**Comment by dduportal** [comment]
Hey folks, I need a careful review on this one, to avoid breaking :)

**Review by timja — APPROVED** [review]
the checks are working which proves most of it

**Review by garethjevans — APPROVED** [review]

**Review by olblak — APPROVED** [review]
I am quite excited to see this PR in action, well done @dduportal

**Pull request merged**
