### PR TITLE
[Updatecli] Update version to v1.9.0

### PR DESCRIPTION
**Pull request by olblak**
**! Experimental project**
This pull request was automatically created using [olblak/updatecli](https://github.com/olblak/updatecli)
Based on a source rule, it checks if yaml value can be update to the latest version
Please carefully review yaml modification as it also reformat it.
Please report any issues with this tool [here](https://github.com/olblak/updatecli/issues/new)

### CODE REVIEW

**Comment by halkeye** [comment]
The new tag exists, so something is broken.

```
reg tags halkeye/jenkins-wiki-exporter | grep v1.10.0
INFO[0000] domain: docker.io
INFO[0000] server address: https://registry-1.docker.io
v1.10.0
```

**Comment by olblak** [comment]
Indeed

**Comment by olblak** [comment]
@halkeye 1.10.0  became a draft version https://github.com/jenkins-infra/jenkins-wiki-exporter/releases, so according the release 1.9.0 is the latest version available.

**Comment by olblak** [comment]
I published the version  1.10.0 on jenkins-infra/jenkins-wiki-exporter

**Comment by halkeye** [comment]
Oooh your using releases not semvsr compare okay

**Comment by olblak** [comment]
As explained [here](https://github.com/olblak/updatecli/#github-release), they are different ways to decide if a value need to be updated, specifically in this case I monitor github releases but we could also monitor version from maven repository, docker image tag by using digest and soon helm version [link](https://github.com/olblak/updatecli/pull/47)

**Pull request closed without merging**
