### PR TITLE
[updatecli] Update Helm Chart version to 2.12.0

### PR DESCRIPTION
**Pull request by olblak**
**! Experimental project**
This pull request was automatically created using [olblak/updatecli](https://github.com/olblak/updatecli)
Based on a source rule, it checks if yaml value can be update to the latest version
Please carefully review yaml modification as it also reformat it.
Please report any issues with this tool [here](https://github.com/olblak/updatecli/issues/new)

### CODE REVIEW

**Comment by olblak** [comment]
Something is wrong with this file

**Comment by olblak** [comment]
This PR was generated based on this [config](https://github.com/jenkins-infra/charts/blob/master/updateCli/updateCli.d/charts/dex.tpl)

**Comment by olblak** [comment]
It should have update dex

**Comment by halkeye** [comment]
Line 20 says datadog

**Comment by halkeye** [comment]
https://github.com/jenkins-infra/charts/blob/master/updateCli/updateCli.d/charts/dex.tpl#L20

**Comment by olblak** [comment]
Yep it assigned the dex version to the datadog file which is obviously wrong

**Comment by olblak** [comment]
Wrong PR

**Pull request closed without merging**
